spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://203.243.17.90:5432/postgres
    username: postgres
    password: postgres
    # jpa properties
    jpa:
      hibernate:
        ddl-auto: create # When you launch the application for the first time - switch "none" at "create"
      show-sql: true
      database: postgresql
      database-platform: org.hibernate.dialect.PostgreSQLDialect
      open-in-view: false
      generate-ddl: true

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace